#!/usr/bin/env python3
"""Dev tool: seed the controls/ tree and data/ reports from a Flipper-IRDB clone.

Walks a clone, runs the package normalizer over every button name, and writes:

  src/ir_canonical/controls/<Name>/aliases.json  - seeded ONLY if absent (hand
                                                    edits are preserved on re-run)
  data/flipper_name_map.json                      - { name: canonical }, folded keys
  data/canonical_controls.yaml                    - full vocabulary by category
  data/unmapped_names.txt                         - the long tail, by frequency

Usage:  python seed.py <path-to-Flipper-IRDB-clone> [data-out-dir]

This is NOT part of the published library — it regenerates the curated tree's
seed from the database; `ir_canonical` itself only ships the tree + compiled map.
"""

import json
import os
import re
import sys
from collections import Counter

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))
from ir_canonical.normalize import CORE, canonical, category_of, title  # noqa: E402

_NAME_RE = re.compile(r"^name:\s*(.+?)\s*$")
_PKG = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src", "ir_canonical")


def tally(clone_dir):
    counts = Counter()
    for root, _dirs, files in os.walk(clone_dir):
        if ".git" in root.split(os.sep):
            continue
        for fn in files:
            if not fn.endswith(".ir"):
                continue
            with open(os.path.join(root, fn), encoding="utf-8", errors="replace") as fh:
                for line in fh:
                    m = _NAME_RE.match(line)
                    if m:
                        counts[m.group(1)] += 1
    return counts


def main(argv):
    if not argv:
        raise SystemExit("usage: seed.py <Flipper-IRDB-clone> [data-out-dir]")
    clone = argv[0]
    out = argv[1] if len(argv) > 1 else os.path.join(os.path.dirname(__file__), "data")
    os.makedirs(out, exist_ok=True)

    counts = tally(clone)
    mapping, unmapped, vocab = {}, [], {}
    mapped_occ = total_occ = 0
    inv = {}
    for raw, n in counts.items():
        total_occ += n
        canon = canonical(raw)
        if canon:
            mapping[raw] = canon
            mapped_occ += n
            vocab.setdefault(category_of(canon), set()).add(canon)
            inv.setdefault(canon, Counter())[raw] += n
        else:
            unmapped.append((n, raw))

    folded = {}
    for raw, canon in mapping.items():
        folded[raw.lower()] = canon
    with open(os.path.join(out, "flipper_name_map.json"), "w", encoding="utf-8") as fh:
        json.dump(dict(sorted(folded.items())), fh, indent=2, ensure_ascii=False)
        fh.write("\n")

    unmapped.sort(reverse=True)
    with open(os.path.join(out, "unmapped_names.txt"), "w", encoding="utf-8") as fh:
        for n, raw in unmapped:
            fh.write(f"{n}\t{raw}\n")

    order = ["power", "volume", "channel", "transport", "navigation",
             "input", "digit", "color", "av", "edit", "app", "gamepad", "other"]
    with open(os.path.join(out, "canonical_controls.yaml"), "w", encoding="utf-8") as fh:
        fh.write("# Canonical media-control vocabulary (generated by seed.py).\n")
        for cat in order:
            if cat not in vocab:
                continue
            fh.write(f"{cat}:\n")
            for canon in sorted(vocab[cat]):
                fh.write(f"  - {canon}\n")

    controls_dir = os.path.join(_PKG, "controls")
    created = preserved = 0
    for name in CORE:
        dedup = {}      # lower -> [best_raw, best_count, total_count]
        for raw, n in inv.get(name, Counter()).items():
            entry = dedup.get(raw.lower())
            if entry is None:
                dedup[raw.lower()] = [raw, n, n]
            else:
                entry[2] += n
                if n > entry[1]:
                    entry[0], entry[1] = raw, n
        aliases = [e[0] for e in sorted(dedup.values(), key=lambda e: -e[2])]
        folder = os.path.join(controls_dir, title(name))
        os.makedirs(folder, exist_ok=True)
        path = os.path.join(folder, "aliases.json")
        if os.path.exists(path):
            preserved += 1
            continue
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(aliases, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        created += 1

    distinct = len(counts)
    print(f"distinct names      : {distinct}")
    print(f"mapped distinct     : {len(mapping)} ({len(mapping) / distinct:.1%})")
    print(f"occurrences mapped  : {mapped_occ}/{total_occ} ({mapped_occ / total_occ:.1%})")
    print(f"controls tree       : {created} created, {preserved} preserved -> {controls_dir}")
    print(f"wrote reports -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
